//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcourCanin
{
    using System;
    using System.Collections.Generic;

    public partial class PARTICIPE
    {
        public string codeproprietaire { get; set; }
        public string codechien { get; set; }
        public string codeconcours { get; set; }
        public Nullable<int> note { get; set; }

        public CHIEN CHIEN
        {
            get => default(CHIEN);
            set
            {
            }
        }

        public CONCOUR CONCOUR
        {
            get => default(CONCOUR);
            set
            {
            }
        }
    }
}
